### ISSUE TITLE
Data read outside of mount points is not registered

### ISSUE THREAD

**Issue by Giancarl021** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#102]
First of all, thank you for the amazing tool provided, it is really helping our team.

**Describe the bug**
After using the [only connector deployment](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.1/deploy-base.md) our team noticied that notebooks dealing with data outside mount points were not being saved on the Purview account.

**To Reproduce**
Follows a sample notebook that causes this behavior:

```py
df = spark.createDataFrame(data=[[1], [2]])
```

```py
df.write.mode("overwrite").parquet("/mnt/lineage-test/df1/")
```

```py
df = spark.read.parquet("/mnt/lineage-test/df1")
```

```py
df.write.mode("overwrite").saveAsTable("test")
```

```py
df2 = table("test")
```

```py
df2.write.mode("overwrite").parquet("mnt/lineage-test/df2/")
```

**Expected behavior**

A databricks notebook lineage with the parquet writes "df2" and "df1", the "df1" parque read and the "test" table read from DBFS.
In a real scenario, we would like to see data writes when APIs are called inside a Databricks Notebook and a internal source when data is coming from outside a mount point.

**Logs**
The full Azure Functions logs can be found in [this gist](https://gist.github.com/Giancarl021/461b43628d7e896f5f624039e5dd23c6). What got my attention was the errors `invalid relationshipDef: process_dataset_outputs: end type 1: DataSet, end type 2: databricks_process` and `Referenced entity AtlasObjectId ... is not found` found in lines [`116`](https://gist.github.com/Giancarl021/461b43628d7e896f5f624039e5dd23c6#file-az-functions-log-L116) and [`200`](https://gist.github.com/Giancarl021/461b43628d7e896f5f624039e5dd23c6#file-az-functions-log-L200), respectively.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenLineage Version: openlineage-spark-0.13.0.jar
 - Databricks Runtime Version: 10.4
 - Cluster Type: Interactive
 - Cluster Mode: Single
 - Using Credential Passthrough: Yes

**Comment by wjohnson** [comment]
Hi @Giancarl021 ! Thank you for using the Solution Accelerator.

Would you be able to try using a data source that is not an in memory relation?  We only support lineage for data sources that are read via the Spark API's like abfss, wasb, and mount points as well as jdbc sources.

For example, could you please try using `df = spark.read.parquet("abfss://storageservice.dfs.windows.core.net/path/to/folder/` instead and let us know if you are seeing lineage?

**Comment by Giancarl021** [comment]
Thank you for the quick response, with other types of sources we could retrieve the lineage. We didn't knew if this was the expected behavior or not, thank you for clarifying that!

**Comment by wjohnson** [comment]
@Giancarl021 We support 

* Azure SQL
* Azure Synapse Analytics
* Azure Data Lake Gen 2
* Azure Blob Storage
* Delta Lake

https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator#features

I wanted to also add that your discovery does appear to be a bug which the PR linked above is working to address.  Thank you for sharing a very easy to use, reproducible sample!  This was a bug I had received from others but could not get details to replicate.  I'm hoping to resolve the issue you are seeing with hive managed tables by the end of next week at the latest.

**Comment by wjohnson** [comment]
@Giancarl021 would you please try upgrading to the latest release of [2.1.1](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/releases/tag/2.1.1)

This should resolve the issue you are seeing with the `invalid relationshipDef: process_dataset_outputs: end type 1: DataSet, end type 2: databricks_process` and `Referenced entity AtlasObjectId ... is not found`.

Again, thank you so much for sharing an easy to understand and reproducible snippet of code.  It was extremely helpful and greatly appreciated!

**Comment by Giancarl021** [comment]
@wjohnson Sorry for the delayed response. I tried to deploy as usual with Azure Cloud Shell, but got the errors shown in [this gist](https://gist.github.com/Giancarl021/03f699b51e761d8a925532d16324a4d6), the error on the lines [3](https://gist.github.com/Giancarl021/03f699b51e761d8a925532d16324a4d6#file-deployment_error_logs-log-L3) and [4](https://gist.github.com/Giancarl021/03f699b51e761d8a925532d16324a4d6#file-deployment_error_logs-log-L4) appeared after approximately 1 hour after execution, so I could not test this version.

Thanks for the feedback, it is greatly appreciated.

**Comment by wjohnson** [comment]
Hey, @Giancarl021 - I'm hoping you're no longer having this issue.  We were able to solve it in the 2.2.2 release that is currently available.  Please give it a try and let us know if we can close this issue.

**Comment by Giancarl021** [comment]
Hello @wjohnson! Sorry for the delayed response! After testing the new [2.3 release](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/tree/release/2.3) with my team, we confirmed that the error was fixed!

Thank you so much for the support.
