### ISSUE TITLE
Purview function app error - cannot acqire exclusive lock

### ISSUE THREAD

**Issue by shkumar64** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#115]
**Describe the bug**
Lineage ingestion fails as function app complains that it can not get the exclusive lock. 
**To Reproduce**
1. Set up databricks in a new env 
2. Use the same fucntions 

**Expected behavior**
Logs are ingested 
**Logs**
[log4j-active (11).txt](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/files/9923330/log4j-active.11.txt)

*
![image](https://user-images.githubusercontent.com/57773810/199577206-a7cc65bd-ca18-4c79-9ae8-109b3d346ce5.png)
![image](https://user-images.githubusercontent.com/57773810/199577411-f9959e0f-40a9-41eb-92d6-7b4284317c53.png)

**Comment by wjohnson** [comment]
Hi, @shkumar64 and thank you for using the solution accelerator.  Based on your screenshot it looks like you're trying to do a deployment to the Azure Function application - the failure is on the "UpdateWebSite" activity in the activity log and not  from Databricks or internal to the application.

From the log4j log you shared it looks like all of the events from Databricks to the Function were succeeding.

Can you share more about the steps you took before this error occurred?  Are you running the ARM template deployment again?

**Comment by shkumar64** [comment]
Thanks for the response will.   This is happening in a customer setup. They ran this accelerator in their dev cluster which was working fine. They wanted to move to a new prod data bricks cluster, so they ended up installing the agent on a new cluster pointing to the same function deployment. 

Not sure, if this heps or is a valid way of operating. I have asked the customer to redeploy it in a fresh env. I will update with results.

**Comment by shkumar64** [comment]
This was resolved up reinstallation.
