### ISSUE TITLE
Lineage not detected using Unity Catalog enabled Cluster

### ISSUE THREAD

**Issue by svnnl** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#117]
Hi there,

In our setup, we've been testing the connector with great success for a pretty basic All-Purpose cluster with no isolation shared. 
Since we also aim to use Unity Catalog, we have tried to test the connector with a Unity Catalog enabled cluster. Given that there's no possibility to edit Init Scripts for UC clusters with Shared Access mode, we have defined the Init Script on a global level. 
Now we've tested that this global init script still ensures that the lineage connector works for the non-UC cluster, but we are not able to make it work for the UC cluster. 

Seems like there are no messages coming in the Azure Functions, even though the clusters have identical setup, apart from the Shared/No isolation shared property which enables the Unity Catalog in our Workspace.

Any idea how to make sure that we can track Lineage using the Unity Catalog enabled cluster? 
Thanks!

**Desktop (please complete the following information):**
 - OS: Windows
 - OpenLineage Version: 0.17.0
 - Databricks Runtime Version: 11.3 LTS
 - Cluster Type: Interactive - Standard DS3_v2
 - Cluster Mode: Unrestricted / Shared Access Mode (UC Enabled)
 - Using Credential Passthrough: No

**Comment by wjohnson** [comment]
Hi, @svnnl - We currently don't support Spark 3.3 which is in the 11.3 LTS.  That is why you're not seeing lineage.

We have been prioritizing a few other features but we will look into testing 11.3 ASAP.

**Comment by svnnl** [comment]
Hi @wjohnson, thanks for your reply, will eagerly await results on the testing and hopefully it can solve the issue.

Just FYI, we do, however, already have a cluster running currently on 11.3 LTS with Spark 3.3 without Unity Catalog enabled and are able to track lineage with it. The only apparent difference between the two clusters is the fact that one has Unity Catalog enabled and the other doesn't (See screenshots below). 

![image](https://user-images.githubusercontent.com/8983696/204504548-2fb57280-8c39-4ead-ace6-c5f6595d3754.png)
Non-UC Cluster with 11.3 LTS - Lineage works.

![image](https://user-images.githubusercontent.com/8983696/204504721-b11bd2b9-00e6-4482-b20d-846b1839a11e.png)
UC Cluster with 11.3 LTS - Lineage doesn't work.

**Comment by rabbyn** [comment]
Hi @wjohnson , @svnnl , I'm confused about the compatibility of this lineage solution for ADB and Unity Catalog support. In this video https://youtu.be/Ae1goH1xOCY?si=OnNRgOGJcT_LTOCf the speaker is saying that it supports only the default Metastore, is that true? Thanks

![Screenshot_2023-10-07-10-53-23-587_com.google.android.youtube-edit.jpg](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/assets/72968975/b7343fa9-ffcb-4782-8421-aa697ab980d6)

**Comment by wjohnson** [comment]
Unfortunately, we won't be able to fix this without a solution from OpenLineage.  [Unity Catalog metadata scanning](https://learn.microsoft.com/en-us/purview/register-scan-azure-databricks-unity-catalog) is supported in Microsoft Purview and Lineage will be coming too.

I will document this limitation in the next release.
