### ISSUE TITLE
source type Azure Blob Storage and Azure Data Lake Storage Gen2 not found after initial run

### ISSUE THREAD

**Issue by isantillan1** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#12]
**Describe the bug**
source type Azure Blob Storage and Azure Data Lake Storage Gen2 not found after initial run

**To Reproduce**
1. run through [Purview-ADB-Lineage-Solution-Accelerator](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator) 
2. check Data Catalog, view 'By source Type'

**Expected behavior**
Expecting to see the image below as per the instructions:
![image](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/raw/main/assets/img/readme/browse_assets.png)

Missing Azure blob Storage and Azure Data Lake Storage Gen 2
![image](https://i.imgur.com/9rr1wOi.png)

**Logs**
1. Please include any Spark code being ran that generates this error
2. Please [include a gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) to the OpenLineageIn and PurviewOut logs
3. See how to stream [Azure Function Logs](https://docs.microsoft.com/en-us/azure/azure-functions/streaming-logs)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - OpenLineage Version: [e.g. name of jar]
 - Databricks Runtime Version: [e.g. 6.4, 9.1, 10.1]
 - Cluster Type: [e.g. Job, Interactive]
 - Cluster Mode: [e.g. Standard, High Concurrency, Single]
 - Using Credential Passthrough: [e.g. Yes, No]

**Additional context**

**Comment by isantillan1** [comment]
1. ![image](https://i.imgur.com/FdBV9Sc.png)
2. ![image](https://i.imgur.com/aHdlwDH.png)
3. ![image](https://i.imgur.com/jexy0O2.png)
4. ![image](https://i.imgur.com/y7Apiwv.png

**Comment by wjohnson** [comment]
@isantillan1 The accelerator [does not create assets outside of the Databricks and `Purview Custom Connector` type definitions](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/main/LIMITATIONS.md#connecting-to-assets-in-purview).

The sample images you saw are based on a catalog that has been scanned.

If you were to scan your data sources and then re-run your notebooks, the lineage would update to point your lineage to the scanned assets.

**Comment by isantillan1** [comment]
Ah, thanks @wjohnson. It was a bit misleading to see the additional source types and the difference in numbers of items found as there were no any additional steps after running the **abfss-in-abfss-out-olsample notebook**. 

Also, seeing a difference of the number of items scanned (3 vs 67) is making me think that something must be off even though I've done what was requested in the instructions.
