### ISSUE TITLE
Databricks Version 10.3 and above are not working

### ISSUE THREAD

**Issue by edkreuk** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#14]
**Describe the bug**
When using a Databricks version 10.3 or above with the applied Advanced Options, the notebook is not starting

**To Reproduce**
Enable cluster with Spark 3.2.1
add advanced option like below

spark.openlineage.version 1 
spark.openlineage.namespace <ADB-WORKSPACE-ID>#<DB_CLUSTER_ID>
spark.openlineage.host https://<FUNCTION_APP_NAME>.azurewebsites.net
spark.openlineage.url.param.code <FUNCTION_APP_DEFAULT_HOST_KEY>

**Expected behavior**
Notebook should work, but since above addition it's not working. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20183155/174042888-5e0bec0d-bd2d-418f-83a5-60a1406d65af.png)

**Desktop (please complete the following information):**

 - OpenLineage Version: [[OpenLineage-Spark 0.8.2 jar](https://repo1.maven.org/maven2/io/openlineage/openlineage-spark/0.8.2/openlineage-spark-0.8.2.jar)]
 - Databricks Runtime Version: [e.g. 6.4, 9.1, 10.1]
 - Cluster Type: [Job]
 - Cluster Mode: [Standard,]
 - Using Credential Passthrough: [e.g. Yes, No]

**Additional context**
Every cluster below Spark 3.2.1 is working fine

**Comment by wjohnson** [comment]
Hi @edkreuk thank you for your continued support and work on this accelerator!  We are working with the OpenLineage team to resolve an issue that is preventing the Databricks runtime from emitting lineage on 10.4 LTS.

If your Spark application can target the 9.1 LTS Databricks Runtime, as you observed, you should be able to collect lineage.

Thank you again for working through the accelerator and engaging with us!
