### ISSUE TITLE
The source Databricks is not registered, Integration Runtime is not created, Scan is not created

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#151]
Carefully following your instructions, we successfully deployed the demo version of Accelerator. There were no errors. and Azure Databricks, Purview, ADLS, Azure Function app (along with its two in and out functions) and example data sources and `one` notebook are all installed. But the following items were `not` installed:

1. Databricks as a source was not registered in the Purview account.
2. Integration Runtime under Purview Portal-->Data Map-->Source Management is empty.
3. Purview Portal-->Management-->Security and Access-->Credential-->Manage Key Vault Connection is empty, and hence there is no credential created.

After I manually registered the Databricks as a source in Purview, I tried to manually create a scan but, as shown below, `Integration Runtime` and `Credential` are required.

**Question**: a) Are the steps 1-3 above not required for this connector or the installation process should have completed these steps? b) Should we be manually complete the above 3 steps?

![image](https://user-images.githubusercontent.com/10931726/215312956-41ad340d-484c-4029-9a78-d64fb79cfe32.png)

**Remarks**: I saw your only one notebook `abfss-in-abfss-out-olsample` with 4 cells in the Databricks. That notebook ran successfully. But there was no lineage created (I assume probably because the above 3 steps were missing and hence there was no scan running). Can you please clarify what we may be missing. I went through your troubleshooting doc but found nothing in the document that may have been missing in the installation.

**OpenLineageIn shows no errors, no success**. Same is true for OpenLineageOut:
![image](https://user-images.githubusercontent.com/10931726/215345203-9f323b47-0463-4146-9317-b2a4e7185b5f.png)

**Comment by wjohnson** [comment]
Hi, @saf-itpro, as per in your other issue, you might be crossing concepts.  This repo is focused on Azure Databricks Notebook and Job lineage.

The recently public preview [Azure Databricks Hive Metastore Connector](https://learn.microsoft.com/en-us/azure/purview/register-scan-azure-databricks) is focused on metastore extraction and lineage back to storage accounts.

Is it okay to close THIS issue in favor of #153 ?
