### ISSUE TITLE
Where is this key located: spark.openlineage.samplestorageaccount

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#158]
The [working connector deployment ](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/deploy-base.md) completed successfully. But when I run the sample notebook `abfss-in-abfss-out-olsample` I get the following error on the code shown below:

>NoSuchElementException: spark.openlineage.samplestorageaccount

**Code**:
```
import org.apache.spark.sql.types.{StructType, StructField, IntegerType, StringType}

val storageServiceName = spark.conf.get("spark.openlineage.samplestorageaccount")
val storageContainerName = spark.conf.get("spark.openlineage.samplestoragecontainer")
val adlsRootPath = "wasbs://"+storageContainerName+"@"+storageServiceName+".blob.core.windows.net"
            
val storageKey = dbutils.secrets.get("purview-to-adb-kv", "storageAccessKey")
            
spark.conf.set("fs.azure.account.key."+storageServiceName+".blob.core.windows.net", storageKey)
```

**Question**:  Is `abfss-in-abfss-out-olsample` notebook valid for the [Connector Only Deployment](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/deploy-base.md), as well. If so, where in the deployment can we find the key `spark.openlineage.samplestorageaccount` in the Databricks?

**Remarks**:
1.  `Spark config` section of the `advanced options` of the cluster look like the following.  The content here is based on the `item 4` of section: [Install OpenLineage on Your Databricks Cluster](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/deploy-base.md#install-openlineage-on-your-databricks-cluster). And as seen below, the key `spark.openlineage.samplestorageaccount` is not present here.
2. I have verified that in the Key Vault (KV), the function app (function's managed identity) is in the KV's access policy.
3. During the execution of the sample notebook, both the Azure Function app and Azure Databricks cluster are running.
4. OpenLineageIn and PurviewOut functions have no errors.
5. In the Azure Function Configuration tab, all the Key Vault Referenced app settings have a green checkmark.

**Spark config**
```
spark.openlineage.version v1 
spark.openlineage.namespace https://adb-8514321158310101.1#0203-044343-1ehjmfc2
spark.openlineage.host https://https://functionappdbrvxka.azurewebsites.net
spark.openlineage.url.param.code "8JWhjPJE-v63S1az4IftDoekwn75CHS4j8ZblrshstxiAzFusbGibA=="
```

**Comment by wjohnson** [comment]
Hi, @saf-itpro - The `spark.openlineage.samplestorageaccount` configuration is used in the demo notebook as you discovered.

If it's not already set, you can update your Databricks spark configuration (Advanced Options, Spark Tab) and add  `spark.openlineage.samplestorageaccount YourStorageAcctName` where YourStorageAcctName is set to the name of the storage account (not the full http url, just the service name that you'd see in the Azure portal).

Alternatively, you can just hard code the storage account name value in the sample notebook instead!

Please let us know if you have any additional questions.  Thank you for working through the solution!

**Comment by wjohnson** [comment]
Closing out for now.  Please let us know if you have any questions or concerns.
