### ISSUE TITLE
azure function (openlineagein) is not getting invoked.

### ISSUE THREAD

**Issue by venugitdevops** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#160]
After deployment, executed below steps. however unable to see the invocation of azure function.

1. Deployed as per connector only deployment.
    Azure functions, event hub got created.
2. Ran a sample notebook in azure data bricks.
3. **issue**: Unable to see the invocation of function app or not seeing any calls in event hub/ function app.

**Comment by wjohnson** [comment]
Thank you for your interest in the Databricks to Purview Solution Acclerator, @venugitdevops!  Would you please run through troubleshooting steps to attempt to resolve the issue?  If you follow the steps there, you will hopefully find a solution.

https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/TROUBLESHOOTING.md

A common issue is if your Purview instance is behind a Private Endpoint, if that's the case, your connector deployment may need to be customized to [use private endpoints](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/docs/private-endpoints.md)

**Comment by wjohnson** [comment]
Closing for now since we haven't heard anything but happy to reopen this if you need any additional information.
