### ISSUE TITLE
Databricks lineage with mounts not getting captured for 11.3 LTS version

### ISSUE THREAD

**Issue by Kishor-Radhakrishnan** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#165]
**Describe the bug**
Databricks lineage with mounts not getting captured for 11.3 LTS version.

Same code with same configurations working fine for 9.1 LTS version 

**To Reproduce**

1. Followed steps mentioned in Connector only deployment.
2. Set up interactive cluster with 11.3 LTS version.
3. Lineage not captured when using mount paths on ADLS Gen1 ( /mnt/mount_name)
4. Lineage captured fine when used direct ADLS Gen1 URI instead of mount ( adl://path)
5. Lineage captured properly in 9.1 LTS version.

Attaching logs from function app 
[dbfs_out_file.txt](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/files/10740476/dbfs_out_file.txt)

**Comment by wjohnson** [comment]
Thank you for your interest and use of the solution accelerator!

11.3 LTS is not officially supported yet but will be in our next release.

If you would like to, you should be able to manually upgrade your
OpenLineage jar to 0.18.0 and that should support mount point extraction on
11.3.

Please let us know if you are able to install the upgraded OpenLineage jar
and test this on your 11.3 cluster.

**Comment by wjohnson** [comment]
Glad to hear it!
