### ISSUE TITLE
Doc Update

### ISSUE THREAD

**Issue by msdya** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#166]
I can see the 2.2 release has support in the code for following data sources  

Hive 
PostgreSQL 
MySQL. 

https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.2/deployment/infra/OlToPurviewMappings.json#L264-L344

However the documentation at 
https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator#features

Does NOT reflect the supported data source, can you update the doc ?  Thanks.

**Comment by hmoazam** [comment]
Good catch! We pushed some of the changes to support the data sources you mentioned, while we were still working on unit and integration tests just to ensure we have everything covered. The next release will have the updates to the docs to specify support for the newer data sources.

**Comment by wjohnson** [comment]
Updated with release/2.3
