### ISSUE TITLE
Purview ADLS Gen1 mount to URL resolve mismatch

### ISSUE THREAD

**Issue by Kishor-Radhakrishnan** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#175]
**Describe the bug**

We are trying out latest version of ADB lineage solution. And we are using mounts in our notebook. But  ADLS URL resolved in purview while using this solution is not matching with actual URL.

URL in purview from solution : adl://accountname.azuredatalakestore.net/lob/ontology/path1/path2/path3

expected actual ADLS Url : adl://accountname.azuredatalakestore.net/datalake-dev/lob/ontology/path1/path2/path3

Mount in Databricks : 

MountPoint - /mnt/datalake/
Source - adl://accountname.azuredatalakestore.net/datalake-dev/

Path used in notebook ( as mount) - /mnt/datalake/lob/ontology/path1/path2/path3

**Comment by wjohnson** [comment]
Thank you @Kishor-Radhakrishnan  for identifying this issue!

I created this hotfix branch to hopefully resolve the issue.  It will require you go redeploy the function and update the OlToPurviewMappings app setting.

New Branch: https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/tree/hotfix/mntDepth
Updated ADLG1 Mapping: https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/hotfix/mntDepth/docs/mappings/adlsg1.json

If you would be able to test this fix we can add this hotfix and your other issue to the latest releases.

**Comment by Kishor-Radhakrishnan** [comment]
@wjohnson  Will it override fix you provided yesterday , I deployed that as well today . I can't see that commit history
 https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/tree/hotfix/librariesInTasks

**Comment by Kishor-Radhakrishnan** [comment]
@wjohnson  Tested it out , Paths resolving properly now . Thanks for the fix again. 

![Screenshot 2023-03-01 at 7 36 15 PM](https://user-images.githubusercontent.com/87746346/222164587-3de0bddb-f30f-42d3-8810-aec4db77a383.png)

**Comment by wjohnson** [comment]
@Kishor-Radhakrishnan thank you for testing! We will get this PR into the release branch as quickly as possible!

**Comment by wjohnson** [comment]
Closing as this made it into main
