### ISSUE TITLE
spark open lineage config as an init script

### ISSUE THREAD

**Issue by Kishor-Radhakrishnan** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#188]
**Describe the bug**
I tried to use below spark config as a global init script.  Script getting succeeded and I can see config in spark UI as well. But jobs are not getting submitted. 

This works fine when giving spark config via UI or ADF job cluster. But we need to run below spark config as an init script for integrating with our workspaces quickly .

cat << 'EOF' > /databricks/driver/conf/00-custom-spark-driver-defaults2.conf
[driver] {
"spark.openlineage.version" = "v1"
"spark.openlineage.namespace" = "adb-263xxxxxxxx.4#default"
"spark.openlineage.host" = "https://functionappxxxxxx.azurewebsites.net"
"spark.openlineage.url.param.code" = "xxxxx"
}

**To Reproduce**
1. use spark config as init script and start a cluster and submit a notebook task.

![Screenshot 2023-03-13 at 1 16 20 PM](https://user-images.githubusercontent.com/87746346/224639472-188716d8-8e82-4319-86f4-2acddd1aed6a.png)

**Comment by wjohnson** [comment]
@Kishor-Radhakrishnan is this the complete global init script you're using?

You may be missing the part where you install OpenLineage if this is not happening in a different init script.

```
STAGE_DIR="/dbfs/databricks/openlineage"
echo "BEGIN: Upload Spark Listener JARs"
cp -f $STAGE_DIR/openlineage-spark-*.jar /mnt/driver-daemon/jars || { echo "Error copying Spark Listener library file"; exit 1;}
echo "END: Upload Spark Listener JARs"
```

Would you be able to confirm the above code is present in your global init script?

If this is present, would you be able to share your log4j logs for a cluster configured with your global init script and submitting a simple job?

**Comment by Kishor-Radhakrishnan** [comment]
Working fine now . Thanks for support . Closing issue
