### ISSUE TITLE
Use Service Principal Certificates instead of Secret Key

### ISSUE THREAD

**Issue by avimelwani** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#19]
**Describe the bug**
Hi Team, 
Our customer security policy doesn't allow the use of secret keys and they would like us to use Service Principal Certificates instead of the Service Principal Secret Key.

**To Reproduce**
1. e.g. use Service Principal Certifcate location to install the solution accelerator.

**Expected behavior**
The Solution Accelerator uses the Service Principal Certificate during the installation and internal communication between the Azure Function and Purview.

**Logs**
1. Please include any Spark code being ran that generates this error
2. Please [include a gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) to the OpenLineageIn and PurviewOut logs
3. See how to stream [Azure Function Logs](https://docs.microsoft.com/en-us/azure/azure-functions/streaming-logs)

**Screenshots**
To use Azuzre Service Principal Certificates for installation and internal app communication.
![image](https://user-images.githubusercontent.com/96129887/174331901-db10bfa3-0cc6-4b62-bd38-74ca52f6ca66.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - OpenLineage Version: [e.g. name of jar]
 - Databricks Runtime Version: [e.g. 6.4, 9.1, 10.1]
 - Cluster Type: [e.g. Job, Interactive]
 - Cluster Mode: [e.g. Standard, High Concurrency, Single]
 - Using Credential Passthrough: [e.g. Yes, No]

**Additional context**

**Comment by wjohnson** [comment]
A few resources to help solve this:

The PurviewCustomType c# helper function needs to use MSAL to get a certificate.

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-differences-adal-net#confidential-client-applications

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1058199/177474593-17db898f-fb71-4d55-bc85-d9255748248e.png)

**Comment by wjohnson** [comment]
@avimelwani with that latest commit to the main branch, we can now support using certificate based authentication for the Azure function.

We are going to do a full release sometime soon but if you want to try it out, you'll need to upload the certificate to a key vault and create an App Setting for the function called `Certificate` and has a value of `{"SourceType": "KeyVault","KeyVaultUrl": "https://MY-KEY-VAULT-SERVICE-NAME.azure.net/","KeyVaultCertificateName": "CertificateNameInAKV"}`
