### ISSUE TITLE
Configurable Custom Type Name

### ISSUE THREAD

**Issue by awbarbeau** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#191]
**Describe the feature**
To improve readability and user experience in using Purview, a configurable name for the Custom Types created on Purview and referenced in the PurviewOut Function App would simplify updates beyond the default value for EntityType.

**Detailed Example**
In [Class for Purview Custom Type](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.3/function-app/adb-to-purview/src/Function.Domain/Helpers/PurviewCustomType.cs), the string "purview_custom_connector_generic_entity_with_columns" is assigned to EntityType. This same string is used in [Infra deployment file for Purview](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.3/deployment/infra/Custom_Types.json), and the [Purview Ingestion Helper](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.3/function-app/adb-to-purview/src/Function.Domain/Services/PurviewIngestion.cs), and at least one test. Instead of a specific value that must be replaced in several files, a configuration option for the custom type, that flows into all relevant components, would allow for additional flexibility during implementation.

**Issues that this feature solves**
None that I know of.

**Suggested Implementation**
For the .cs classes, adding a value in the [settings](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.3/function-app/adb-to-purview/src/Function.Domain/Models/Parser/Settings/AppConfigurationSettings.cs) would seem the simplest approach, and then the EntityType is updated to reference the value in each respective class.

I don't have a suggestion for the [Infra Custom_Types.json](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.3/deployment/infra/Custom_Types.json), not sure how this could be done effectively.

Maintaining a default value such as "purview_custom_connector_generic_entity_with_columns" would be reasonable for implementations that don't have an ask in this space. 

**Additional context**
Thanks again for all the work on the accelerator!

**Comment by wjohnson** [comment]
Thank you for the suggestion! Unfortunately, we won't be able to commit to this but would be glad to take on a PR if you're interested in contributing!
