### ISSUE TITLE
Function App is triggered but no messages are created

### ISSUE THREAD

**Issue by arvidlb** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#240]
**Describe the bug**
After deployment, running a notebook properly triggers the OpenLineageIn function. Event hub receives succesful requests but no messages are being created.

**To Reproduce**
1. Databricks Runtime Version 14.3 (though this does not seem to matter because triggering the function from Postman yields the same result
2. Run Notebook or trigger the function from Postman with a sample payload
3. Postman returns "{\"message\":\"Successfully ingested OpenLineage event\"}"
4. Eventhub shows the same number of incoming and succesful requests
5. Messages queue stays empty
6. Logs do no show errors
7. Storage account .avro files are empty

**Expected behavior**
A message should be created in the queue so that PurviewOut gets triggered

**Logs**
Application insights and realtime logs show nothing of interest.

**Screenshots**
![Image](https://github.com/user-attachments/assets/8cb556a1-5b37-4184-9e8f-b4014b40e6cf)

**Desktop (please complete the following information):**
 - OpenLineage Version: Latest
 - Databricks Runtime Version: 14.3
 - Cluster Type: Interactive
 - Cluster Mode: -
 - Using Credential Passthrough: -

**Additional context**
I have tried redirecting the Key Vault sb endpoint to .../<EventHubName>/messages instead of the default https://<EventHubName>.servicebus.windows.net but to no avail.

**Comment by arvidlb** [comment]
I have some updated info, though I am still not sure what the appropriate route is to fix the issue. I have added extra logging lines to the OpenLineageIn function. This tells me that the payload never passes the `if (_olFilter.FilterOlMessage(strRequest))` check.

However, strRequest is not empty. And the payload also has a valid namespace attribute. Im using the following sample payload:

`{
  "eventTime": "2024-10-29T16:19:07.283Z",
  "producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
  "schemaURL": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunEvent",
  "eventType": "COMPLETE",
  "run": {
    "runId": "0192d912-79f6-7c2a-a751-f8d5b483615e",
    "facets": {
      "parent": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/ParentRunFacet.json#/$defs/ParentRunFacet",
        "run": {
          "runId": "0192d910-e992-70b0-bad8-2e3382b49204"
        },
        "job": {
          "namespace": "default",
          "name": "databricks_shell"
        }
      },
      "spark_properties": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet",
        "properties": {
          "spark.master": "spark://10.139.64.12:7077",
          "spark.app.name": "Databricks Shell"
        }
      },
      "processing_engine": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/facets/1-1-1/ProcessingEngineRunFacet.json#/$defs/ProcessingEngineRunFacet",
        "version": "3.5.0",
        "name": "spark",
        "openlineageAdapterVersion": "1.23.0"
      }
    }
  },
  "job": {
    "namespace": "default",
    "name": "adb-1217703170417694.14.azuredatabricks.net.atomic_replace_table_as_select.default_temp",
    "facets": {
      "jobType": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/facets/2-0-3/JobTypeJobFacet.json#/$defs/JobTypeJobFacet",
        "processingType": "BATCH",
        "integration": "SPARK",
        "jobType": "SQL_JOB"
      }
    }
  },
  "inputs": [],
  "outputs": [
    {
      "namespace": "dbfs",
      "name": "/user/hive/warehouse/temp",
      "facets": {
        "dataSource": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet",
          "name": "dbfs",
          "uri": "dbfs"
        },
        "schema": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-1-1/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet",
          "fields": [
            {
              "name": "a",
              "type": "long"
            },
            {
              "name": "b",
              "type": "long"
            }
          ]
        },
        "storage": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/StorageDatasetFacet.json#/$defs/StorageDatasetFacet",
          "storageLayer": "unity",
          "fileFormat": "parquet"
        },
        "symlinks": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/SymlinksDatasetFacet.json#/$defs/SymlinksDatasetFacet",
          "identifiers": [
            {
              "namespace": "dbfs:/user/hive/warehouse",
              "name": "default.temp",
              "type": "TABLE"
            }
          ]
        },
        "lifecycleStateChange": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/LifecycleStateChangeDatasetFacet.json#/$defs/LifecycleStateChangeDatasetFacet",
          "lifecycleStateChange": "OVERWRITE"
        }
      },
      "outputFacets": {
        "outputStatistics": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/1.23.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-2/OutputStatisticsOutputDatasetFacet.json#/$defs/OutputStatisticsOutputDatasetFacet",
          "rowCount": 0,
          "size": 0
        }
      }
    }
  ]
}`

I feel like the `if (_olFilter.FilterOlMessage(strRequest))` is there to check if the payload is not empty, which its not. Yet it doesn't pass the check. There's also not an else statement for this particular if statement, which means a succesful HTTP request still results in a: 

`"{\"message\":\"Successfully ingested OpenLineage event \"}"`

Logging rule.

**Comment by gvrspk17** [comment]
Hi arvidlb, were you able to capture the lineage from databricks to purview ?
