### ISSUE TITLE
Authentication token expiration is not checked if retrieved from cache

### ISSUE THREAD

**Issue by uhrb** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#45]
There are no checks around authentication token expiration when cached. In case of token expired, it will lead to returning expired token to calling function. 
All calling functions as for now do not check expiration of the token.

https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/cc4dd14fe75e95c7c8d070fd925f0929dfcbd742/function-app/adb-to-purview/src/Function.Domain/Helpers/PurviewCustomType.cs#L707

**Comment by wjohnson** [comment]
@l0nley are you getting an explicit error message that you could share?

**Comment by wjohnson** [comment]
Closing due to age and our observation that token caching is updating on long running jobs. But please feel free to reopen if you are observing the cache is not being updated.

**Comment by mwferris** [comment]
I am maybe running into this issue. I am manually running a notebook in Databricks and getting this error:

![image](https://user-images.githubusercontent.com/29456597/234667997-b72f3daf-16f2-4028-b8b4-8baeba3ca7d9.png)

The same code worked yesterday and created lineage in Purview. Checking the code I found:

[This](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/7f4da3af98dabd7f8fd35951d4682836e34689b3/function-app/adb-to-purview/src/Function.Domain/Services/PurviewIngestion.cs#L178) line is getting logged among others that indicate an expired token.

[This](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/7f4da3af98dabd7f8fd35951d4682836e34689b3/function-app/adb-to-purview/src/Function.Domain/Helpers/PurviewCustomType.cs#L658) function doesn't check the expiry of the token and just loads from the cache, which might cause the issue.

Any help would be appreciated!
