### ISSUE TITLE
Databricks cluster failure with error as "Init script failure"

### ISSUE THREAD

**Issue by apatelkgl** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#48]
**Describe the bug**
Databricks cluster is getting failed with error as "Cluster terminated. Reason: Init script failure"

**To Reproduce**
Deploy Cluster with 9.1 LTS Runtime version

Spark Config
spark.openlineage.url.param.code <FUNCTION_APP_DEFAULT_HOST_KEY>
spark.openlineage.namespace <DATABRICKS_URI_NO>#default
spark.openlineage.version 1
spark.openlineage.host https://<FUNCTION_APP_DEFAULT_HOST_KEY>.azurewebsites.net

Init Script

#!/bin/bash
STAGE_DIR="/dbfs/databricks/openlineage"
cp -f $STAGE_DIR/openlineage-spark-*.jar /mnt/driver-daemon/jars || { echo "Error copying Spark Listener library file"; exit 1;}
cat << 'EOF' > /databricks/driver/conf/openlineage-spark-driver-defaults.conf
[driver] {
  "spark.extraListeners" = "io.openlineage.spark.agent.OpenLineageSparkListener"
}
EOF

**Expected behavior**
Cluster should be start successfully with mentioned Init script.

**Logs**
1. Please include any Spark code being ran that generates this error
2. Please [include a gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) to the OpenLineage In and PurviewOut logs
3. See how to stream [Azure Function Logs](https://docs.microsoft.com/en-us/azure/azure-functions/streaming-logs)

**Screenshots**
![image](https://user-images.githubusercontent.com/91620016/180140060-8c63211b-7a42-4051-864c-9c025afbd1b7.png)

**Desktop (please complete the following information):**
 - OpenLineage Version: [openlineage-spark-0.9.0.jar]
 - Databricks Runtime Version: [9.1]
 - Cluster Mode: Standard

**Additional context**
Without Init script Databricks cluster gets started successfully,

**Comment by wjohnson** [comment]
Hi, @apatelkgl This is likely due to carriage returns in the init script.  I'm assuming you're using a Windows machine.

Please follow these instructions on adjusting your file to use only line feeds or even setting up your git configuration to use only linefeeds when cloning a repo.

https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/1.1/TROUBLESHOOTING.md#demo-deployment-r-command-not-found

**Comment by apatelkgl** [comment]
Hey, Will (@wjohnson), Thanks for pointing out.

Yes, i am on windows system only.

As suggested, Re-writed file in databricks directly and that  resolved the issue.

Thanks again @wjohnson :)
