### ISSUE TITLE
adb cluster json is malformed. 

### ISSUE THREAD

**Issue by Sam-Panda** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#66]
while deploying the "demo deployment". The json for the ADB cluster creation is getting malformed for some reason., and the cluster is not getting created by the script. 

![image](https://user-images.githubusercontent.com/29522070/182689852-e3c6082a-8b9c-4b5e-be51-74eae2f3c200.png)

Here is the error message in the CLI
![image](https://user-images.githubusercontent.com/29522070/182690242-b1434c74-aafe-4639-95fa-55edff4d8e3d.png)

**Comment by marktayl1** [comment]
Thank you, this should be resolved in release 2.0.1.
