### ISSUE TITLE
Picture link in readme is broken

### ISSUE THREAD

**Issue by sonnyhcl** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#7]
**Describe the bug**
Just saw this project from internal talk and open it. Found the picture link in readme is broken to see

**To Reproduce**
1. e.g. data sources and destination being used
2. e.g. code snippet to generate the error

**Expected behavior**

**Logs**
1. Please include any Spark code being ran that generates this error
2. Please [include a gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) to the OpenLineageIn and PurviewOut logs
3. See how to stream [Azure Function Logs](https://docs.microsoft.com/en-us/azure/azure-functions/streaming-logs)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - OpenLineage Version: [e.g. name of jar]
 - Databricks Runtime Version: [e.g. 6.4, 9.1, 10.1]
 - Cluster Type: [e.g. Job, Interactive]
 - Cluster Mode: [e.g. Standard, High Concurrency, Single]
 - Using Credential Passthrough: [e.g. Yes, No]

**Additional context**

**Comment by wjohnson** [comment]
@sonnyhcl -  Would you be able to take a screenshot or share a deep link to the section that looks broken?  From our side, we cannot find a broken image on any of the markdown documents.  Thank you for taking a look and giving us a hand!

**Comment by wjohnson** [comment]
@sonnyhcl  - I'm going to close this for now but please let us know if you can share what you're seeing and we can re-open and resolve it.
