### ISSUE TITLE
ADF executing notebooks is getting error

### ISSUE THREAD

**Issue by tgpmoraes** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#72]
**Describe the bug**
I have deployed the demo environment, after that, I created an ADF to execute the notebook. The pipeline present a success status, but the information is not showing in Purview

**To Reproduce**
1. Deploy the demo environment
2. Deploy Azure Data Factory
3. Create a Linked Service using Access Token generated in the workspace for authentication
4. Choose a new cluster
5. Add cluster setting as follow:
![image](https://user-images.githubusercontent.com/8151342/183933378-89783bfe-5834-47ba-b2ee-b448b64f506a.png)
6. I needed to change the workspace from spark.openlineage.namespace, because the value created from the deployment wasn't right - adbpurviewol1

**Expected behavior**
I am expecting the lineage be pushed to purview

**Logs**
PurviewOut
`2022-08-10T14:27:55.269 [Error] AdbClient-GetSingleAdbJobAsync: error, message: Response status code does not indicate success: 403 (Forbidden).Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: AdbClient-GetSingleAdbJobAsync: error, message: Response status code does not indicate success: 403 (Forbidden).Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()at Function.Domain.Providers.AdbClientProvider.GetSingleAdbJobAsync(Int64 runId, String adbWorkspaceUrl) in D:\a\Purview-ADB-Lineage-Solution-Accelerator\Purview-ADB-Lineage-Solution-Accelerator\function-app\adb-to-purview\src\Function.Domain\Providers\AdbClientProvider.cs:line 127Stack:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()at Function.Domain.Providers.AdbClientProvider.GetSingleAdbJobAsync(Int64 runId, String adbWorkspaceUrl) in D:\a\Purview-ADB-Lineage-Solution-Accelerator\Purview-ADB-Lineage-Solution-Accelerator\function-app\adb-to-purview\src\Function.Domain\Providers\AdbClientProvider.cs:line 127`

**Desktop (please complete the following information):**
 - OpenLineage Version: The same available in the github from this week
 - Databricks Runtime Version: 9.1
 - Cluster Type: Cluster created during the ADF execution
 - Cluster Mode: Standard
 - Using Credential Passthrough: No

**Comment by rodrigomonteiro-gbb** [comment]
Hey Tiago, you need to follow this step to have jobs working https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.0/deploy-base.md#support-extracting-lineage-from-databricks-jobs

**Comment by tgpmoraes** [comment]
Hi Rodrigo,
I was able to follow this step and make it work.
I don't if it is right or not, but when we execute through Data Factory, it is generated a job on Databricks, and the job name concatenates an hexadecimal where in Purview for each time that I run the job, it is creating a new entry.
I know that it makes sense, as it is a job, but I don't know if Purview is the best place to keep history of execution, instead, I would rather prefer seeing only on job for the specific job.

Could you please help me understand the correct approach? We need to share this with the customer.

![image](https://user-images.githubusercontent.com/8151342/184008024-dff2f13e-e4aa-4bfa-8f4d-e575a1f474cb.png)
As you can see, it is the same pipeline and the same notebook, but with **3 entries**.

**Comment by wjohnson** [comment]
@tgpmoraes that is unfortunately a limitation we are inheriting due to the ADF team.  They are creating ADF runs / Databricks  jobs with this naming convention and it is undocumented / an implementation detail in the eyes of the ADF team.

If the naming convention really, really is irksome, you could modify the code to check to see if the job name follows that pattern and then extract the parts (which look like `ADF_<factory name>_<pipeline name>_<task name>_<guid>`) and construct the preferred name.

**Comment by tgpmoraes** [comment]
@wjohnson if we follow the path to modify the code as you mentioned, would it be possible to push it into the main branch? Otherwise the customer will have dificulties to merge all the time new features come up from the accelerator.

Currently the lineage that has been generated by ADF is not helping, take a look:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/8151342/185404846-f3e779c8-1727-4e8b-9d1f-5384cc9abea1.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/8151342/185404828-23cc7093-d630-46e4-be5e-908535b21636.png)

**Comment by wjohnson** [comment]
We would GLADLY accept contributions.  However, how else would you expect the lineage to look like?

It seems like they are using one parameterized notebook in their ADF pipeline, right?  

What else would you show in the lineage graph and how would you distinguish between parameterized ADF notebook runs?

**Comment by ivarostby** [comment]
Thanks for highlighting this. It's an important improvement for our team as well. Are you working on a PR, @tgpmoraes?

**Comment by wjohnson** [comment]
@tgpmoraes - Okay!  We've reached out to the product team and gained confirmation that this pattern is stable.

Would youe or @ivarostby be able to test this branch? https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/tree/feature/handleADFNaming

**Comment by wjohnson** [comment]
You can find the built zip of the code in #137

**Comment by wjohnson** [comment]
With the release of #2.3.0 this is now enabled!
