### ISSUE TITLE
regarding the spark config

### ISSUE THREAD

**Issue by Sam-Panda** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#73]
As per the script : openlineage-deployment.sh
the below value of the spark config is the workspace name
    "spark_conf": {
        "**spark.openlineage.namespace" : "adbpurviewol1#default",**

In the connector-only configuration page, it is given as below
https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.0/deploy-base.md

**spark.openlineage.namespace <ADB-WORKSPACE-ID>#<DB_CLUSTER_ID>**

is it expected?

**Comment by wjohnson** [comment]
Hi, @Sam-Panda yes this is for demonstration purposes only.  If you want to use the demo cluster for working through a job, you'll need to follow the more advanced connector only deployment.
