### ISSUE TITLE
Databricks "openlineage-demo" cluster cannot start

### ISSUE THREAD

**Issue by marjan-radfar** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#76]
Hello,
After deploying the demo using "deploy-demo.md", the databricks cluster could not start due to the following error:

Summary

Message
Cluster terminated. Reason: Secret resolution error

Help
Internal error resolving secrets.

Error message: Failed to fetch secrets referred to in Spark Conf

JSON

`{
  "reason": {
    "code": "SECRET_RESOLUTION_ERROR",
    "type": "SERVICE_FAULT",
    "parameters": {
      "databricks_error_message": "Failed to fetch secrets referred to in Spark Conf"
    }
  }
}`

I checked the secrets and the keyvault's secret was the same as the service principal (with data curator role in the Purview account).

**Comment by csnarain** [comment]
@marjan-radfar Is the demo deployment even working for you? For me, the deployment fails in deploying the function app and aborts. I've opened #75 for the same.

**Comment by marktayl1** [comment]
Could you please verify that the keyvault backed secret scope was created successfully?  

[Secret scopes - Azure Databricks | Microsoft Docs](https://docs.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes#--list-secret-scopes)

**Comment by marjan-radfar** [comment]
> @marjan-radfar Is the demo deployment even working for you? For me, the deployment fails in deploying the function app and aborts. I've opened #75 for the same.

Thanks @csnarain for your comment. I have not been successful yet. I read your issue, it was helpful, and gonna deploy the recent release tag (2.0.4)

**Comment by marjan-radfar** [comment]
> Could you please verify that the keyvault backed secret scope was created successfully?
> 
> [Secret scopes - Azure Databricks | Microsoft Docs](https://docs.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes#--list-secret-scopes)

Thanks for your comment. Would you please help me find the scope and scope_name? It's not clear to me what to do exactly. When I replaced `{{secrets/purview-to-adb-kv/Ol-Output-Api-Key}}` with `FUNCTION_APP_DEFAULT_HOST_KEY`  in `spark.openlineage.url.param.code {{secrets/purview-to-adb-kv/Ol-Output-Api-Key}}` inside Spark Configuration, the cluster could start. But I assume the cluster should start automatically when I deploy the demo.

**Comment by marjan-radfar** [comment]
> > Could you please verify that the keyvault backed secret scope was created successfully?
> > [Secret scopes - Azure Databricks | Microsoft Docs](https://docs.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes#--list-secret-scopes)
> 
> Thanks for your comment. Would you please help me find the scope and scope_name? It's not clear to me what to do exactly. When I replaced `{{secrets/purview-to-adb-kv/Ol-Output-Api-Key}}` with `FUNCTION_APP_DEFAULT_HOST_KEY` in `spark.openlineage.url.param.code {{secrets/purview-to-adb-kv/Ol-Output-Api-Key}}` inside Spark Configuration, the cluster could start. But I assume the cluster should start automatically when I deploy the demo.

@marktayl1 I was able to [create secret scope in Azure Databricks](https://bigdataprogrammers.com/create-secret-scope-in-azure-databricks/#:~:text=There%20are%20two%20types%20of%20secret%20scope%20available,encrypted%20database%20owned%20and%20managed%20by%20Azure%20Databricks.) and got the lineage in Purview.

**Comment by wjohnson** [comment]
Glad you were able to get it up and running, @marjan-radfar !  Please let us know if you run into any other issues.
