### ISSUE TITLE
How to get the lineage after deploying the Connector?

### ISSUE THREAD

**Issue by marjan-radfar** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#84]
Hello,

I deployed all steps in the "[Connector Only Deployment](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/main/deploy-base.md)". Now, how can I see the databricks lineage in my Purview account? I've uploaded a sample notebook with input/output csv files. I'd appreciate it if you could help me with the steps.

**Comment by csnarain** [comment]
@marjan-radfar if you installed the connector only, then either create a notebook and execute some spark activities or copy the sample notebook that comes with default deployment and execute that. Once executed, head to purview portal and browse for assets by source type which will show azure databricks asset and underneath it you'll find your notebook name which will contain the metadata info for the activities

**Comment by csnarain** [comment]
@wjohnson Will this connector capture lineage info if I copy my source files from dbfs? For eg., I was trying to process some csv files from dbfs (my blob storage mountpoint resides here), did some ETL and then copied that to a sql table in Azure Synapse. Unfortunately, no lineage info is shown for this activity.

**Comment by wjohnson** [comment]
> @wjohnson Will this connector capture lineage info if I copy my source files from dbfs? For eg., I was trying to process some csv files from dbfs (my blob storage mountpoint resides here), did some ETL and then copied that to a sql table in Azure Synapse. Unfortunately, no lineage info is shown for this activity.

Hi, @csnarain first thank you for helping to answer @marjan-radfar 's question!

With respect to your concern, are you using a command like `spark.read.csv("/mnt/path")` and then writing it using the [Databricks Synapse Connector](https://docs.microsoft.com/en-us/azure/databricks/data/data-sources/azure/synapse-analytics)?  There is a [limitation on the Synapse connector](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.0/LIMITATIONS.md#azure-synapse-sql-pools) which we hope to resolve in another release.

However, you should be able to see lineage. Would you be able to open a separate issue and share a minimum viable code snippet so we could replicate?

**Comment by csnarain** [comment]
@wjohnson yes, I'm using command like spark.read.csv("/mnt/path"). I'll open a separate issue for this.

**Comment by marjan-radfar** [comment]
> @marjan-radfar if you installed the connector only, then either create a notebook and execute some spark activities or copy the sample notebook that comes with default deployment and execute that. Once executed, head to purview portal and browse for assets by source type which will show azure databricks asset and underneath it you'll find your notebook name which will contain the metadata info for the activities

Thanks @csnarain for your help :) When I compared the connector with the demo, I realized the keyvault and secret creation also have to be done separately. I think this was the missing part.
