### ISSUE TITLE
Purview Lineage metadata reporting Issue

### ISSUE THREAD

**Issue by csnarain** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#92]
I configured this connector using the accompanying script and did the following activities.

1. Created a python script in ADB notebook
2. Mounted Azure Blob Storage (Gen2) using dbfs over a mountpoint
3. Invoked Microsoft Graph API and saved the output as csv
4. Copied the csv to Blob Storage mountpoint
5. Read the csv back from the mountpoint to a spark dataframe
6. Did some ETL operations like removed rows with null values (using spark drop function), renamed columns (using withColumnRenamed) and stored the results in a new dataframe
7. Using a jdbc connector, copied the dataframe (from step 6) to a Synapse SQL datapool
8. Triggered a stored procedure in Synapse from ABD notebook

Now, when I goto purview portal and browse the ADB notebook asset, I see only the following reported in Lineage visualization

![image](https://user-images.githubusercontent.com/9998645/187030437-37aca9bc-a948-48a0-ae71-3d2b7a5665ce.png)
None of the ETL operations in step 6 are shown. I understand that stored procedures are not reported but I was expecting at least the ETL operations to show up. Am I doing anything wrong?

**Comment by wjohnson** [comment]
Thanks for using the solution accelerator, @csnarain !  Currently, the Purview UI is not capable of displaying the transformations that occur in your spark notebook / task.  Right now, your experience is looking accurate in that it successfully identified the read from blob and write to Synapse. That's the maximum the UI can show for now.

You can see the logical plan in the related `databricks_process` (see the Notebook's Advanced Properties section for a hyperlink to the process).  The logical plan provides you with a json description of each class involved in your transformations but it's not very user friendly to look at ☹️

I hope that helps and we greatly appreciate you taking the time to ask these great questions and really explore the accelerator!

**Comment by wjohnson** [comment]
Closing given the thumbs up and > 30 days open.
